version: '3'

services:
  postgres:
    image: postgres:12
    ports:
      - "$DB_PORT:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  redis:
    image: redis:6.2
    ports:
      - 6378:6379
  app:
    build: .
    command: sh -c "python manage.py migrate
      #             && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis
    restart: always