# Generated by Django 4.0.3 on 2022-03-23 23:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 23, 31, 6, 871956)),
        ),
    ]
