# Generated by Django 4.0.3 on 2022-03-24 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_employment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 24, 19, 35, 13, 46528)),
        ),
    ]
